export const Routes = {
    LOGIN: {
        path: "/",
        title: "Login",
        metaTitle: "Login",
        metaDescription: "Login",
    },
    SIGNUP: {
        path: "/signup",
        title: "Create new account",
        metaTitle: "Create new account",
        metaDescription: "Create new account",
    },
    HOME: {
        path: "/home",
        title: "Home",
        metaTitle: "Home",
        metaDescription: "Home",
    },
    FRIEND: {
        path: "/friend",
        title: "Friend",
        metaTitle: "Friend",
        metaDescription: "Friend",
    },
    FRIEND_AllREQUEST: {
        path: "/friend/allRequest",
        title: "Friend Requests",
        metaTitle: "Friend Requests",
        metaDescription: "Friend Requests",
    },
    FRIEND_AllFRIENDS: {
        path: "/friend/friendlist",
        title: "All friends",
        metaTitle: "All friends",
        metaDescription: "All friends",
    },
    SAVED: {
        path: "/saved",
        title: "Saved",
        metaTitle: "Saved",
        metaDescription: "Saved",
    },
    VIDEO: {
        path: "/video",
        title: "Video",
        metaTitle: "Video",
        metaDescription: "Video",
    },
    VIDEO_SAVED: {
        path: "/video/saved",
        title: "Saved Videos",
        metaTitle: "Saved Videos",
        metaDescription: "Saved Videos",
    },
    GROUP: {
        path: "/group/:id",
        title: "Group",
        metaTitle: "Group",
        metaDescription: "Group",
    },
    GROUP_ABOUT: {
        path: "/group/:id/about",
        title: "About",
        metaTitle: "Group About",
        metaDescription: "Group About",
    },
    GROUP_PEOPLE: {
        path: "/group/:id/people",
        title: "People",
        metaTitle: "Group People",
        metaDescription: "Group People",
    },
    GROUP_MEDIA: {
        path: "/group/:id/media",
        title: "Media",
        metaTitle: "Group Media",
        metaDescription: "Group Media",
    },
    GROUP_CREATE: {
        path: "/group/create",
        title: "Group",
        metaTitle: "Group",
        metaDescription: "Group",
    },
    GROUP_FEED: {
        path: "/group/feed",
        title: "Your feed",
        metaTitle: "Group Feed",
        metaDescription: "Group Feed",
    },
    GROUP_DISCOVER: {
        path: "/group/discover",
        title: "Discover",
        metaTitle: "Group Discover",
        metaDescription: "Group Discover",
    },
    GROUP_JOINED: {
        path: "/group/joins",
        title: "Your groups",
        metaTitle: "Group Joined",
        metaDescription: "Group Joined",
    },
    FEED: {
        path: "/feed",
        title: "Feed",
        metaTitle: "Feed",
        metaDescription: "Feed",
    },
    FEED_FRIENDS: {
        path: "/feed/friends",
        title: "Feed Friends",
        metaTitle: "Feed Friends",
        metaDescription: "Feed Friends",
    },
    STORY: {
        path: "/story/:id",
        title: "Story",
        metaTitle: "Story",
        metaDescription: "Story",
    },
    STORY_CREATE: {
        path: "/story/create",
        title: "Create Story",
        metaTitle: "Create Story",
        metaDescription: "Create Story",
    },
    REEL: {
        path: "/reel/:id",
        title: "Reel",
        metaTitle: "Reel",
        metaDescription: "Reel",
    },
    REEL_CREATE: {
        path: "/reel/create",
        title: "Create Reel",
        metaTitle: "Create Reel",
        metaDescription: "Create Reel",
    },
    PROFILE: {
        path: "/profile/:id",
        title: "Profile",
        metaTitle: "Profile",
        metaDescription: "Profile",
    },
    PROFILE_ABOUT: {
        path: "/profile/:id/about",
        title: "Intro",
        metaTitle: "About",
        metaDescription: "About",
    },
    PROFILE_VIDEO: {
        path: "/profile/:id/video",
        title: "Video",
        metaTitle: "Video",
        metaDescription: "Video",
    },
    PROFILE_PHOTO: {
        path: "/profile/:id/photo",
        title: "Photo",
        metaTitle: "Photo",
        metaDescription: "Photo",
    },
    PROFILE_FRIEND: {
        path: "/profile/:id/friend",
        title: "Friend",
        metaTitle: "Friend",
        metaDescription: "Friend",
    },
};
