export const Routes = {
    LOGIN: {
        path: "/",
        title: "Login",
        metaTitle: "Login",
        metaDescription: "Login",
    },
    SIGNUP: {
        path: "/signup",
        title: "Create new account",
        metaTitle: "Create new account",
        metaDescription: "Create new account",
    },
    HOME: {
        path: "/home",
        title: "Home",
        metaTitle: "Home",
        metaDescription: "Home",
    },
    FRIEND: {
        path: "/friend",
        title: "Friend",
        metaTitle: "Friend",
        metaDescription: "Friend",
    },
    FRIEND_AllREQUEST: {
        path: "/friend/allRequest",
        title: "Friend Requests",
        metaTitle: "Friend Requests",
        metaDescription: "Friend Requests",
    },
    FRIEND_AllFRIENDS: {
        path: "/friend/friendlist",
        title: "All friends",
        metaTitle: "All friends",
        metaDescription: "All friends",
    },
    GROUP: {
        path: "/group",
        title: "Group",
        metaTitle: "Group",
        metaDescription: "Group",
    },
    GROUP_LIST: {
        path: "/group/grouplist",
        title: "Your Groups",
        metaTitle: "Your Groups",
        metaDescription: "Your Groups",
    },
    SAVED: {
        path: "/saved",
        title: "Saved",
        metaTitle: "Saved",
        metaDescription: "Saved",
    },
    VIDEO: {
        path: "/video",
        title: "Video",
        metaTitle: "Video",
        metaDescription: "Video",
    },
    VIDEO_SAVED: {
        path: "/video/saved",
        title: "Saved Videos",
        metaTitle: "Saved Videos",
        metaDescription: "Saved Videos",
    },
    BOOKMARK: {
        path: "/bookmark",
        title: "Bookmark",
        metaTitle: "Bookmark",
        metaDescription: "Bookmark",
    },
    REEL: {
        path: "/reel",
        title: "Reel",
        metaTitle: "Reel",
        metaDescription: "Reel",
    },
    PROFILE: {
        path: "/profile",
        title: "Profile",
        metaTitle: "Profile",
        metaDescription: "Profile",
    },
    PROFILE_ABOUT: {
        path: "/profile/about",
        title: "Intro",
        metaTitle: "About",
        metaDescription: "About",
    },
    PROFILE_VIDEO: {
        path: "/profile/video",
        title: "Video",
        metaTitle: "Video",
        metaDescription: "Video",
    },
    PROFILE_PHOTO: {
        path: "/profile/photo",
        title: "Photo",
        metaTitle: "Photo",
        metaDescription: "Photo",
    },
    PROFILE_FRIEND: {
        path: "/profile/friend",
        title: "Friend",
        metaTitle: "Friend",
        metaDescription: "Friend",
    },
    POST: {
        path: "/post",
        title: "Post",
        metaTitle: "Post",
        metaDescription: "Post",
    },
};
